default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%= ENV['DATABASE_NAME'] %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: 3306 #<%= ENV['DATABASE_PORT'] %>

 

development:
  <<: *default

 

test:
  <<: *default
  database: moove_test

 

production:
  <<: *default

 

staging:
  <<: *default
 

# default: &default
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   database: <%= ENV['DATABASE_NAME'] %>
#   pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
#   username: <%= ENV['DATABASE_USERNAME'] %>
#   password: <%= ENV['DATABASE_PASSWORD'] %>
#   host: <%= ENV['DATABASE_HOST'] %>
#   port: <%= ENV['DATABASE_PORT'] %>

# development:
#   <<: *default

# test:
#   <<: *default
#   database: moove_test

# production:
#   <<: *default

# staging:
#   <<: *default
